server:
  port: 9008

spring:
  application:
    name: service-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

turbine:
  app-config: service-feign, service-ribbon
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")

